import './globals.css'
import { Dongle, Roboto } from 'next/font/google'

const roboto = Roboto({ 
  weight: ['300', '400', '500'],
  subsets: ['latin'],
  variable: '--roboto'
})

const dongle = Dongle({
  subsets: ['latin-ext'],
  weight: ['400'],
  variable: '--dongle'
})

export const metadata = {
  title: 'Home - NerdCollection',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${dongle.variable} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  )
}
